### ISSUE TITLE
Deprecate py27?

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#117]
Should we deprecate py27 support?

**Comment by drdhaval2785** [comment]
Currently there are no layman users for the commandline tool.
Only developers would fire these python scripts from commandline.
They can easily download python3 and run the code. Nowadays most linux distros also ship with python3 by default.
So it makes sense to drop python2 support.

**Comment by avinashvarna** [comment]
I agree. Most major python libraries such as [numpy](https://www.numpy.org/neps/nep-0014-dropping-python2.7-proposal.html) stopped adding new features for py27 earlier this year. We could adopt a similar stance in that old releases will still be available, but new updates/features only support python 3.6+

**Comment by kmadathil** [comment]
Since @vvasuki recommended this, we'll presume another vote in favor. So, let's go ahead with this.

**Comment by kmadathil** [comment]
If I try to remove the py27 environment from the tox configuration, travis starts showing XML errors. I do not see these while running tox on my machine. 
Please see the no27 branch

**Comment by avinashvarna** [comment]
I wonder whether this is some instability in travis, because I had to rerun build [202](https://travis-ci.org/kmadathil/sanskrit_parser/builds/533637510) a couple of times before it passed. And that build was just an update to the README! 
Rerunning build [208](https://travis-ci.org/kmadathil/sanskrit_parser/builds/534344438) also seems to have caused it to pass.

**Comment by kmadathil** [comment]
I merged no27, and now I don't see a travis job being kicked off. Something funny is going on.

**Comment by kmadathil** [comment]
Successfully merged.
