### ISSUE TITLE
Web service

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#134]
Our old web service is out of date. We need to set up a new one or update the code on the old one. @vvasuki had indicated he did not have access to that server any more.

I will set up an EC2 server temporarily, but we need a more scalable solution. Possibly, a serverless solution like AWS Lambda.

**Comment by kmadathil** [comment]
I have a very basic setup running on a EC2 micro server. Ideally, this needs a load balancer and multiple workers behind it to handle any serious load. I have not got the graphs working yet for some reason.
The setup is gunicorn + nginx reverse proxy
I have mapped the url skt_parser_api.madathil.org (a domain I own) to the EC2 server address. Again, this needs to be through something more flexible.

**Comment by gasyoun** [comment]
And there will be an API, right, as well?

**Comment by avinashvarna** [comment]
@gasyoun There has been an API for a long time. The web site/server is really just to host the API. E.g. take a look at http://skt_parser_api.madathil.org/sanskrit_parser/v1/splits/astyuttarasyAMdizi

**Comment by avinashvarna** [comment]
@kmadathil Is it possible to add a [let's encrypt](https://letsencrypt.org/) SSL certificate and enable HTTPS? Currently, the request from the [UI](https://kmadathil.github.io/sanskrit_parser/ui/index.html) is blocked on both FF and Chrome since the https UI webpage is trying to load unencrypted content.

**Comment by avinashvarna** [comment]
My bad. Just saw your note about enabling mixed content. It wasn't in the email, and I missed it.

**Comment by vvasuki** [comment]
@kmadathil Could you share how you got the  EC2 micro server running? step-by-step procedure, script etc.. so that the path is easier for future coders.

**Comment by kmadathil** [comment]
@avinashvarna - I'll add HTTPS too soon
@vvasuki - sure, I will add documentation to the repo on how to replicate this.

**Comment by kmadathil** [comment]
@gasyoun - Our API library lets you play with it directly using this URI
http://skt_parser_api.madathil.org/sanskrit_parser/docs

**Comment by kmadathil** [comment]
README_ec2.md added with a description of steps to bring this basic setup up

**Comment by kmadathil** [comment]
Updated to enable https - need not enable mixed_content now

**Comment by avinashvarna** [comment]
I have a basic version working at https://sanskrit-parser.appspot.com based on the fixes for #148 and #151. The REST API can be accessed in the usual way. E.g. https://sanskrit-parser.appspot.com/sanskrit_parser/v1/splits/astyuttarasyAm

Navigating to the base URL https://sanskrit-parser.appspot.com redirects to the UI that is already available (https://kmadathil.github.io/sanskrit_parser/ui/index.html) and sets the `api_url_base` to the app engine URL, so that the UI works properly as well.

Note that the first time the URL is accessed, there may be a slight lag as the App Engine container is initialized and booted. Also, parsing long sentences (in "Analyze vAkya" mode in the UI) times out. We may need to further improve the performance for containerized platforms that are computationally constrained.

**Comment by kmadathil** [comment]
Nice! 

The View Graph links result in a 404. There's a static directory that needs to be created and dot must be installed. Not sure how that works in appspot.

**Comment by avinashvarna** [comment]
Appspot filesystem is read-only. If we need the graphs, we should return the .dot graph in the JSON response and use a graph plotting library such as https://github.com/dagrejs/dagre-d3 to display it client-side

**Comment by kmadathil** [comment]
@avinashvarna - can you update the appspot installation to the latest master. It's currently broken for vakya analysis because the front end is expecting something that the older backend doesn't provide.

**Comment by avinashvarna** [comment]
Done. The graphs are pretty cool with image-charts. 👍 Thanks for updating the UI!

I've updated the default api_url_base to sanskrit-parser.appspot.com in the UI (just in case someone has bookmarked the previous link). 

The charges for the appspot engine are negligible. So I'm ok with letting it be on all the time. I think this issue can be closed now, if you think so too.

**Comment by kmadathil** [comment]
Closing

**Comment by kmadathil** [comment]
Reopening to discuss update procedure

@avinashvarna  - can we add an action to automatically push code on release to appspot? (We can do updates asynchronously in-between releases as needed).
I was doing the pypi update asynchronously, I've now added an action to push to pypi on every release. I'll plan to be more formal on releases as well.
