### ISSUE TITLE
Implement a better Sandhi class

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#16]
Assigning to @avinashvarna  

Things I'd like to see
1) A class rather than a function
2) Automated scheme for defining sandhi patterns and generating methods to do the work
3) Automated scheme for deriving sandhi reversal from forward sandhi

We have basic sandhi reversal working, but we should do this properly.

**Comment by avinashvarna** [comment]
Created branch avinashvarna and pushed my changes. (Documentation and logging took up a long time!)
I think the solution meets your requirements 1-3 above. I've also tried to isolate the actual rules from the code, so that they can be updated/proofread by someone without intimately understanding the code. Rules are stored in .txt files in the sandhi_rules subdirectory. Currently there are just a handful of rules, so that we can test out the architecture. Then, it's just a question of writing up the rules.
The convention to write the rules are also documented in the .txt files in the sandhi_rules subdir.
Feedback and comments are welcome. 

In the meantime, I will try to write up a testing framework.

**Comment by drdhaval2785** [comment]
Went through structure.
From my experience in encodings  AVOID unicode Devanagari. It has hell lot of issues.
Let us stick to SLP1 for internal representation. The most annoying part of unicode Devanagari is that 

क् is represented as क+~`।×÷={}

**Comment by avinashvarna** [comment]
The class only expects/uses devanagari for the rules read from the external file because they need to be entered by a human. I think SLP1 for that could be error-prone. (At least personally, I can't read/write SLP1.) If we also want to get it validated by any classical scholars, it would be useful to have the sandhi rules written in devanagari.

The only other place unicode devanagari is being used is for the simple tests that are currently in the script. I plan to remove them and switch to a pytest based testing framework with the tests coming from an external file, so this will go away soon.

**Comment by avinashvarna** [comment]
Updated to use pytest framework. Will remove the other tests in sandhi.py shortly.
Running py.test in sanskrit_parser directory (or lexical_analyzer subdir) should show something similar to:
$ py.test
============================= test session starts =============================
platform win32 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: C:\Users\ALVARNA\Documents\personal\samskritam\research\sanskrit_parser, inifile:
collected 50 items

lexical_analyzer\test_sandhi.py ..................................................

========================== 50 passed in 0.18 seconds ==========================

Will work on adding more rules and tests. Am planning to use the sandhi-extracted entries from this corpus (http://sanskrit.uohyd.ac.in/Corpus/). Will try to figure out the license. Otherwise, may have to reconstruct DCS database

**Comment by kmadathil** [comment]
Nice!

I'll look through in more detail soon. Some quick comments
1. Integration with SanskritObject will make life easier. Convert all strings into SanskritObjects, and use the transcoded version when required. (I see you've noted this). This will mean that rules and tests can be written in any encoding and will all work magically/seamlessly together.
2. At first sight, I like the way you've expanded rules instead of using regexps.  
3. See if you can use the MaheshvaraSutras class to make rule writing easier. That allows you to write the rules in terms of pratyAhAras instead of regexps. You can use the getPratyahara method to convert, say "ik" into a list of varNas, or use isInPratyahara('u','ik') to check if u is an ik (Those actually take SanskritObjects instead of strings as I've shown for simplicity). 
4. You have a few more rules to implement in hal sandhi, which I guess you know. Should be straightforward to convert the rules that're already in SanksritLexicalAnalyzer.

**Comment by avinashvarna** [comment]
1. Yes, that will certainly make life easier. It's on the TODO list.
2. I thought about this initially, and figured that it might be better to expand them once while adding the rules, instead of looping over all keys each time while splitting/joining. Now lookups will be O(1), instead of O(# of rules).
3. I will look into using the MaheshvaraSutras class more. Initially, my thought was that directly using the pratyAhAras in the sUtras would lead to invalid cases. e.g. iko yaNachi would imply i + i = yi, which is incorrect because of akaH savarNe dIrghaH. So I felt that explicitly writing them out would help avoid such situations. Let me think more about it.
4. A lot more rules to implement :). I am poring through the sandhi book by shrI mahAbaleshvara-bhaTTaH, and trying to cover as many as possible. Not sure if we want to add every single one though, as it can lead to a lot of unnecessary splits. E.g. in ach_sandhi.txt I have a comment about whether we want to add vAnto yi pratyaye. I think a test-driven approach would be better here (i.e. add these niche rules if we encounter any tests that fail). Thoughts?

**Comment by drdhaval2785** [comment]
>I thought about this initially, and figured that it might be better to expand them once while adding the rules, instead of looping over all keys each time while splitting/joining. Now lookups will be O(1), instead of O(# of rules).

It is possible to rewrite the order of Paninian rules so that they are applied sequentially for most of the time.

I had mentioned this possibility in my paper at http://www.sanskritworld.in/index/detailview/book_id/prakriyapradarshini.
Here is the article for easy reference.
See section 4, 9 and 10 for some ideas.
I may be able to give rules to be applied in a linear order.

[prakriyapradarshini.pdf](https://github.com/kmadathil/sanskrit_parser/files/1133504/book_55bcd36f9b0ca.1.pdf)

**Comment by kmadathil** [comment]
> I will look into using the MaheshvaraSutras class more. Initially, my thought was that directly using the pratyAhAras in the sUtras would lead to invalid cases. e.g. iko yaNachi would imply i + i = yi, which is incorrect because of akaH savarNe dIrghaH. So I felt that explicitly writing them out would help avoid such situations. Let me think more about it.

What we need is rule groups to handle these things. In a rule group, apply only the rule with the highest priority that is triggered.अकः सवर्णे दीर्घः is higher priority than इको यणचि. Similarly एङः पदान्तादति is higher priority than एचो अयवायावः . MaheshvaraSutras will help even more in getting traditional scholars to review our rule groups.

> A lot more rules to implement :). I am poring through the sandhi book by shrI mahAbaleshvara-bhaTTaH, and trying to cover as many as possible. Not sure if we want to add every single one though, as it can lead to a lot of unnecessary splits. E.g. in ach_sandhi.txt I have a comment about whether we want to add vAnto yi pratyaye. I think a test-driven approach would be better here (i.e. add these niche rules if we encounter any tests that fail). Thoughts?

I can help in adding rules once you've got rule groups implemented. वान्तो यि प्रत्यये should not be added, since we aren't splitting pratyayas.

**Comment by kmadathil** [comment]
> It is possible to rewrite the order of Paninian rules so that they are applied sequentially for most of the time.

This is great. Let me look through in more detail.

**Comment by avinashvarna** [comment]
@drdhaval2785 
Thanks for the paper. Will look through it. In this context though, I think you misunderstood me. I didn't mean looping over the sUtras to apply them one after the other. More in terms of looping over the rules/regexps we have in our database to determine whether there is a match.

@kmadathil 
Implementing priority groups sounds like a good idea, but I fear that it might end up being too complex for our application. I have currently implemented a simple set based notation instead. E.g. [*अच् - इई] will mean all अच् except for इ and ई. So इको यणचि may be written as [इ, ई] + [*अच् - इई] = य्{1}. Hopefully this is ok for now.

I've implemented all the rules I could find in the sandhi reference book I have. It ends up being an impressive 2k+ rules database:
`>>> import sandhi`
`>>> s = sandhi.Sandhi()`
`>>> len(s.forward)`
`2259`
`>>> len(s.backward)`
`2129`

I also added a feature whereby if we turn on DEBUG logging, it will log which file;linenum rule is being used to perform the join/split for every match, so that we can easily trace back joins/splits to the rules files.

I think we are ready for testing now. I will focus on adding more tests from now on, and will fix bugs as we find them by running tests.

**Comment by drdhaval2785** [comment]
>I didn't mean looping over the sUtras to apply them one after the other. More in terms of looping over the rules/regexps we have in our database to determine whether there is a match.

It pretty much means the same.
And priority groups idea of kmadathil also means the same.

Let me clarify the issue with example.
1. Panini has 4000 rules, majority of them for string modification.
2. We have an input string and a set of attributes with it.
3. All 4000 rules can apply any time it finds regex matched. 
4. Let us say that a Paninian derivation gets over in 10 rules.
5. So every time the system searches whether any of 4000 rules is applicable or not. (Whether regexes match from our database).
So total 10 * 4000 = 40000 lookups.

What I propose is an ordered list of rules. So we traverse and check for regex match only 4000 times. Once the rules are exhausted, thata it. You have your output string.

In our toy example, rules will be ordered like below.
1. अकः सवर्णे दीर्घः
२.  इको यणचि

So when लक्ष्मी+इति sees rule 1, it gets changex to लक्ष्मीति.
Now rule 2 is tested. There is no ik followed by ac now. So rule 2 is not applied.

So even if you have written इक्+अच्=यण् in your rule set, it will not matter. The string will be in modified state. So second rule will not match.

There is no need to modify it to exclude iI.

**Comment by kmadathil** [comment]
@avinashvarna 
This is coming out really well! Since you've got this far, let's go with this approach  [इ, ई] + [*अच् - इई] = य्{1} for now. 

One problem I see is the visarga sandhi. We need to start from forms ending with s and r in the forward direction, and end with s/r forms in the backward direction. 
  1. That's the only way we can distinguish ramogacCati and punarapi in both directions. 
  2. The INRIA db stores forms ending in s and r, not visarga.

For reasons of ease of use, it might be ok to let the forward pass allow ramaH + gacCati (which actually never happens in the Paninian scheme. It's ramas gacCati - ramar(u) gacCati - ramo gacCati), but not the backward pass.

**Comment by avinashvarna** [comment]
Thanks. I think we should start integrating it with the main lexical analyzer code, and think about testing the overall system we have so far. 
My unit testing is progressing reasonably well. Running on all two word sandhis in this file: http://sanskrit.uohyd.ac.in/Corpus/CIIL/Vinodini/vinodini-ext.txt (which just happens to be the first link on the corpus page) gives:
============================= 
collected 1734 items
=================== 127 failed, 1607 passed in 3.90 seconds ===================
Some of these are just weird unicode characters in the middle of the file that are throwing off the assertions, and some are incorrect splits in the file. I am working on cleaning this up and hope to get the passing rate much higher.

Regarding visarga sandhis, since we are ok with the splitter generating a super set of splits including some lexically invalid splits, and let the next level handle them, I currently have the rules set up to allow all forms both ways. (This is actually true for all rules. Any thing that is possible in the foward join is also a backward split.) When we look up the split in the word database, we would end up automatically throwing away splits that end in visarga. I think this is an acceptable trade-off between a practical easy to implement solution and strictly implementing aShTAdhyAyI sUtras.

A practical example:
$ python sandhi.py --split punarapi 4
Splitting punarapi at 4
[[u'punA', u'fapi'], [u'puna', u'Fapi'], [u'punA', u'Fapi'], [u'puna', u'fapi'], [u'punaH', u'api'], [u'punar', u'api'], [u'punas', u'api'], [u'punaf', u'api'], [u'punaF', u'api']]

Note that punas/r/H api are all returned in the splits, but some would be discarded by the next level if the corresponding form is not in the db. Ditto for rAmogacCati:

$ python sandhi.py --split rAmogacCati 3
Splitting rAmogacCati at 3
[[u'rAm', u'ogacCati'], [u'rAmas', u'agacCati'], [u'rAmo', u'agacCati'], [u'rAmar', u'agacCati'], [u'rAma', u'ugacCati'], [u'rAmA', u'ugacCati'], [u'rAmaH', u'agacCati'], [u'rAma', u'UgacCati'], [u'rAmA', u'UgacCati'], [u'rAmas', u'gacCati'], [u'rAmar', u'gacCati'], [u'rAmaH', u'gacCati']]

In the forward join
$ python sandhi.py --join raamas gacCati
Joining raamas gacCati
[u'rAmo gacCati', u'rAmogacCati', u'rAmargacCati', u'rAmaHgacCati']

$ python sandhi.py --join raamar gacCati
Joining raamar gacCati
[u'rAmo gacCati', u'rAmogacCati', u'rAmargacCati', u'rAmaHgacCati']

The last two may not be valid sandhied forms, but this is the trade off I was referring to. On the other hand, it does allow the following to be computed correctly:
$ python sandhi.py --join raamar ""
Joining raamar
[u'rAmaH']

$ python sandhi.py --join raamas ""
Joining raamas
[u'rAmaH']

**Comment by kmadathil** [comment]
I have pushed a branch with a more canonical DAG implementation. Please check if you can integrate with that.

**Comment by kmadathil** [comment]
Closing this as this is integrated.
