### ISSUE TITLE
Cache VakyaGraphNode str representations

### ISSUE THREAD

**Issue by avinashvarna** [kmadathil/sanskrit_parser#160]
Investigating ways to speed up parsing (to partially address #148 as well as enable better app_engine performance), I discovered that there is a lot of logging in `datastructures.py` that makes 1000s of calls to `VakyaGraphNode.__str__`, which cumulatively consumes a lot of time.

From what I can see, the VakyaGraphNode class should be considered immutable (i.e. it is not modified after creation). If so, we can cache the str representation at creation time. Just this change reduced the parse time significantly (~30%) on the fix_148 branch to parse a single split.
```bash
$ time python profile_test.py
 Split: ['asti', 'uttarasyAm', 'diSi', 'devatA', 'AtmA']
....
real    0m10.109s
```
```bash
$ time python profile_test.py
 Split: ['asti', 'uttarasyAm', 'diSi', 'devatA', 'AtmA']
....
real   0m6.785s
```
The change is to compute the current output of `__str__`  at `init` and save it for use later:
```diff
@@ -765,6 +765,8 @@ class VakyaGraphNode(object):
     def __init__(self, sobj, index):
         self.pada = sobj
         self.index = index
+        self._str = str(self.pada) + " " + str(self.pada.getMorphologicalTags()) + \
+                " " + str(self.index)

     def getMorphologicalTags(self):
         return self.pada.getMorphologicalTags()
@@ -803,8 +805,7 @@ class VakyaGraphNode(object):
         return self.path.index(node.pada.canonical())

     def __str__(self):
-        return str(self.pada) + " " + str(self.pada.getMorphologicalTags()) + \
-            " " + str(self.index)
+        return self._str
```

@kmadathil Is `VakyaGraphNode` immutable? Can we make this change?

**Comment by kmadathil** [comment]
`VakyaGraphNode` was intended to be mutable, but I don't actually see any case where it is being used mutably now. The plan in my head for implementing samuccaya relies on mutability, but I haven't done that yet. However, we could still do it the way you mention, and provide an interface for mutability that computes `self._str`. 

Also,
 1. Most of those are logger.debug, so should this matter when we're not running in debug mode? At least that's what I thought. This is a good gotcha to keep in mind - though the logger.debug doesn't cause a result, the f string is evaluated anyways, which is why we see the delay.
 2. I would expect `VakyaGraphNode` to matter only for parse, not split - which I presume is what you're seeing as well.

**Comment by avinashvarna** [comment]
If we implement the fields using the `property` decorator and getters/setters, then the `self._str` could be updated any time one of the fields change, allowing for mutability.
1. This was a gotcha for me as well, though it makes sense in hindsight.
2. Yes, only for the parse. So it doesn't address #148 directly, but I was doing a lot of profiling for that as well.

**Comment by kmadathil** [comment]
Agree. Do you want to do that as part of your speedup branch or do you want me to commit this independently? I'm ok either way

**Comment by avinashvarna** [comment]
I can make this change. Regarding the speedups, we should have a separate
discussion on the pros and cons. I will update #148 and related issues with
the details.
