### ISSUE TITLE
App Engine Push broken?

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#181]
I made a new release with the new UI code, and https://sanskrit-parser.appspot.com/ doesn't work any more. Did I do something incorrect?

**Comment by avinashvarna** [comment]
Looking at the logs, and googling the error, it appears to be due to this issue - https://github.com/python-restx/flask-restx/issues/460. The latest push caused the container to be rebuilt, which surfaced this error. The solution suggested [here](https://stackoverflow.com/questions/73105877/importerror-cannot-import-name-parse-rule-from-werkzeug-routing) is to pin the version of `werkzeug` until this issue is fixed.

**Comment by avinashvarna** [comment]
I've pinned werkzeug version and changed the github workflow to run on any tag push of `v*` as well. I've tagged it v0.2.4-post2, but it's not reflected in the library version shown in the UI

**Comment by kmadathil** [comment]
Thanks for fixing this. The library version requires a modification to `sanskrit_parser/__init__.py`. I have bumped the version to 0.2.4-post3 and also pushed a tag v0.2.4-post3. This version is now correctly reflected in the UI. I am not making a release as this doesn't affect any of the functionality in 0.2.4
