### ISSUE TITLE
constraint module error

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#38]
```
$ python SanskritMorphologicalAnalyzer.py 'astyuttarasyAMdishi'
Traceback (most recent call last):
  File "SanskritMorphologicalAnalyzer.py", line 11, in <module>
    import constraint
ImportError: No module named constraint
```
Maybe this is needed in the required modules list.

**Comment by drdhaval2785** [comment]
After this installation of python-constraint module,
The following error is seen.
Something to do with the class and method.

```
$ python SanskritMorphologicalAnalyzer.py astyuttarasyAMdishi
Input String: astyuttarasyAMdishi
Input String in SLP1: astyuttarasyAMdiSi
Start Split: 2017-08-10 09:58:27.457000
Traceback (most recent call last):
  File "SanskritMorphologicalAnalyzer.py", line 262, in <module>
    main()
  File "SanskritMorphologicalAnalyzer.py", line 243, in main
    graph=s.getSandhiSplits(i,tag=True,debug=args.debug)
TypeError: getSandhiSplits() got an unexpected keyword argument 'tag'
```

**Comment by kmadathil** [comment]
Please use the morpho branch for SanskritMorphologicalAnalyzer.py for now. I have not merged with master/integ because I'm seeing some test issues. I will fix those and merge. 

(morpho)$ python SanskritMorphologicalAnalyzer.py 'astyuttarasyAMdishi' 
Input String: astyuttarasyAMdishi
Input String in SLP1: astyuttarasyAMdiSi
Start Split: 2017-08-10 10:51:27.046867
End DAG generation: 2017-08-10 10:51:27.061373
End pathfinding: 2017-08-10 10:51:27.064938
Splits:
Lexical Split: [asti, uttarasyAm, diSi]
Valid Morphologies
[(asti, ('as#1', set([ekavacanam, praTamapuruzaH, ekavacanam, law, prATamikaH, kartari]))), (uttarasyAm, ('uttara#2', set([saptamIviBaktiH, strIliNgam, ekavacanam]))), (diSi, ('diS#2', set([dvitIyAviBaktiH, napuMsakaliNgam, bahuvacanam])))]
[(asti, ('as#1', set([ekavacanam, praTamapuruzaH, ekavacanam, law, prATamikaH, kartari]))), (uttarasyAm, ('uttara#2', set([saptamIviBaktiH, strIliNgam, ekavacanam]))), (diSi, ('diS#2', set([saptamIviBaktiH, strIliNgam, ekavacanam])))]
[(asti, ('as#1', set([ekavacanam, praTamapuruzaH, ekavacanam, law, prATamikaH, kartari]))), (uttarasyAm, ('uttara#1', set([saptamIviBaktiH, strIliNgam, ekavacanam]))), (diSi, ('diS#2', set([dvitIyAviBaktiH, napuMsakaliNgam, bahuvacanam])))]
[(asti, ('as#1', set([ekavacanam, praTamapuruzaH, ekavacanam, law, prATamikaH, kartari]))), (uttarasyAm, ('uttara#1', set([saptamIviBaktiH, strIliNgam, ekavacanam]))), (diSi, ('diS#2', set([saptamIviBaktiH, strIliNgam, ekavacanam])))]
...

**Comment by kmadathil** [comment]
इदानीम् morpho शाखा master/integ इति शाखयोः समाविष्टा | तस्मादस्य विषयं पिदधामि
