### ISSUE TITLE
Test enhancements for sandhi and lexical analyzer

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#47]
Some of the UoHD tests for these aren't passing. We've seen issues with the files themselves , which could be causing many of the failures. And of course, we're far from having all our issues ironed out.

I've not given enough thought to this, but this is what I have in mind
1) Create a simple script to run all the UoHD tests, automatically extract the passing ones, and add them to a pass set that's automatically run
2) Extract the currently failing tests, and move them to a separate fail list so they can be run individually and checked. 
3) The default regression should run all the passing tests from 1 plus the manually created reference tests (which all pass)

**Comment by kmadathil** [comment]
Also, lexical analyzer tests make some automatic modifications to UoHD data to correct some seemingly obvious errors. We need a way to automatically extract the original and modified versions and review them for correctness

**Comment by avinashvarna** [comment]
I can work on 1 and 2 above to get me restarted on this project, if @codito can help with the CI portion which would be part of 3.

**Comment by codito** [comment]
Sure, I will get started with the CI part.

**Comment by kmadathil** [comment]
Great, I'll wait for this to make similar changes to the LexicalAnalyzer tests.

**Comment by avinashvarna** [comment]
Created a test_improvement branch and a script to partition the sandhi tests into currently passing and failing. In the pytest script (still test_sandhi.py), instead of running only the passing tests, the failing tests are marked as xfail (expected to fail). Pytest should not treat them as errors, which should allow our CI to run correctly. I thought this was a good mechanism to ensure that the failing tests are also run, so that we can track the improvement as we fix any issues.

Take a look and let me know if this is good. We can then make similar changes to the lexical analyzer test using the UoHD data.

In the meantime, I will work on extracting the changes made by the lexical analyzer test to the UoHD data and reviewing them. I think these account for a lot of the sandhi failures as well, so it would be good to clean them up.

**Comment by kmadathil** [comment]
Looks good.

**Comment by avinashvarna** [comment]
Thanks.

How do we want to review the modifications made by test_uohd_SanskritLexicalAnalyzer? I dumped out all the changes in the first 10000 refs, and there are too many to review manually (~4500) even if we eliminate the basic ones with the random punctuation marks. If we then remove the ones with the words where we replaced a word-ending anusvAra with a makaara, only 82 remain. At this point, they are all ones with a visarga missing at the end (as that is the only other change that SanskritLexicalAnalyzer makes). This is a small enough number to review manually. I have been doing this by dumping the data into two files, and using a diff tool to compare the changes side by side. Should I just check in these two files so that everyone else can review them as well, or do you have something else in mind?

**Comment by codito** [comment]
The approach looks great to me. Can we add an additional field to the `failing*.txt` files? E.g. `(before) input`, `(after) expected` and `actual`. We can compare the `expected` and `actual` fields for fixing the failing tests.

**Comment by kmadathil** [comment]
@avinashvarna - yes, that'll do perfectly well, thank you!

**Comment by codito** [comment]
@kmadathil it seems travis requires admin permissions for initial link with github repo. Can you please help out with steps 1 and 2 in [this doc](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI)?

**Comment by kmadathil** [comment]
@codito - done (I think)

**Comment by codito** [comment]
@kmadathil thanks the integration is working! We have a PR for CI config here: https://github.com/kmadathil/sanskrit_parser/pull/49

**Comment by kmadathil** [comment]
@codito - Nice. 

@avinashvarna  I've begun a similar task on the LexicalAnalyzer tests. In addition to the changes you've noted, the LexicalAnalyzer tests skip a lot of lines that cannot be tested because a) The forms required are not in the db or b) an exception is thrown due to an input that cannot be handled. I'll split tests into pass,fail,skip, and exception. We will need to deal with each differently.

**Comment by codito** [comment]
We have fixed the failing tests in CI PR #49. It is now ready for code review.

**Comment by kmadathil** [comment]
@avinashvarna @codito should we enable all branches for CI?

**Comment by kmadathil** [comment]
I've made the changes to SanskritLexicalAnalyzer tests in the test_improvement branch and pushed it. CI passes (tests run for nearly half an hour though!). 
Now to debug stuff :-)
