### ISSUE TITLE
Sandhi quality.

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#7]
Sandhi is currently backtracked using this technique

```
         self.sandhi_map = dict([
            ('A',('A_','a_a','a_A','A_a','A_A','As_')),
            ('I',('I_','i_i','i_I','I_i','I_I')),
            ('U',('U_','u_u','u_U','U_u','U_U')),
            ('F',('F_','f_f','f_x','x_f','F_x','x_F','F_F')),
            ('e',('e_','e_a','a_i','a_I','A_i','A_I')),
            ('o',('o_','o_a','a_u','a_U','A_u','A_U','aH_','aH_a','a_s')),
            ('E',('E_','a_e','A_e','a_E','A_E')),
            ('O',('O_','a_o','A_o','a_O','A_O')),
            ('ar',('af','ar')),# FIXME Why is this
            ('d',('t_','d_')),
            ('H',('H_','s_')),
            ('S',('S_','s_','H_')),
            ('M',('m_','M_')),
            ('y',('y_','i_','I_')),
            ('N',('N_','M_')),
            ('Y',('Y_','M_')),
            ('R',('R_','M_')),
            ('n',('n_','M_')),
            ('m',('m_','M_')),
            ('v',('v_','u_','U_')),
            ('r',('r_','s_','H_'))])
```
 if a character in a string matches a key, it's optionally replaced by each of the replacements in the map, split with _ to yield a  string to replace the match char, and prepend to the right context, respectively.

This does a good bit, but does not fully and accurately capture all sandhi backtracking. We need a better method.

**Comment by avinashvarna** [comment]
The library mentioned in #6 (https://github.com/sanskrit/sanskrit) appears to handle left and right contexts for joins, but not for splits. For splits, it uses a trie data structure (http://ellard.org/dan/www/Q-97/HTML/root/node22.html) to lookup splits, with the trie internally implemented as a dict.

Mbykov's sandhi.js https://github.com/mbykov/sandhi appears to implement splits using if/else statements.

For simplicity, it might be simplest to extend the above map using (left, curr, right) characters as the key in a dict with the values being set of possible splits. We could write a wrapper that takes a set of sandhi joining rules and builds such a dict. Then each joining rule could be annotated with the sutra, etc.

The only difficulty I can think of currently is that some valid sandhis/splits require morphological information. 
E.g. prAtaH + bhajati -> prAtarbhajati (because prAtaH is an avyaya)
so if we have (a, r, B), splitting it as (aH, B) is only valid if the resulting left word is an avyaya. (For most subantas, aH + B -> o + B)
For now, we may have to punt this kind of checking to a higher layer.

**Comment by kmadathil** [comment]
Agree with the idea - let me look at this a bit more.

And yes, there are some morphological and contextual catches to Sandhi - the one I remember is puraskaroti. There is also duHkha, which I think is infamously unPaninian. We can handle this by implementing a superset of splits, and use morphological rules later to reject bad ones (we will need morphological rules anyways to throw out the morphologically bad splits)

Minor nitpick - Correct me if I've got it wrong, but I think prAtarbhajati is because prAtar is a rakArAnta, which doesn't trigger the `ato rorapludAdaplute` sutra. That needs `sasajusho ruH` to have happened to a sakaranta (which is what you get when sup is added to an akAranta prAtipadika). We can handle that by storing forms as sakArAnta or rakArAnta in the database (as Prof. Huet seems to have done) instead of storing them with a visarga. That's actually more Paninian too.

**Comment by kmadathil** [comment]
TRIE would actually be a very good datastructure to store the XML lexical databses in. It would speed up the search pretty significantly compared to the current XPATH search. We could convert from XML to TRIE in python, pickle it, and load the pickled version to save conversion time.

**Comment by avinashvarna** [comment]
I actually wrote up a simple module somewhat similar in concept to https://github.com/sanskrit/sanskrit since I had spare time on a flight. Will create a branch and check it in so that we can all review it and improve it.

Regarding prAtarbhajAmi, I think you are right. Clearly I am not as well versed with my aShTAdhyAyI as I should be :)

Regarding the trie, I think a dict will suffice, but we can discuss it in the other issue.

**Comment by kmadathil** [comment]
@avinashvarna 
I'll open a new issue to track your sandhi class implementation so I can close this one. 
Contexts seem to be working fine per your suggestion above. I'm not 100% done, but I could get all the sutras I could remember done. Will add more after poring through my notes.
