### ISSUE TITLE
kAntA - we need to think of promoting the sanskrit_util branch 

### ISSUE THREAD

**Issue by kmadathil** [kmadathil/sanskrit_parser#82]
Reported by @drdhaval2785

python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer --split kaScitkAntAvirahaguruRA
Input String: kaScitkAntAvirahaguruRA                                                                                                                                                  
Input String in SLP1: kaScitkAntAvirahaguruRA                                                                                                                                          
Start Split: 2017-12-22 08:33:00.288657                                                                                                                                                
End DAG generation: 2017-12-22 08:33:00.296659
End pathfinding: 2017-12-22 08:33:00.299814
Splits:
[kaH, cit, kA, antA, viraha, guruRA]
[kaH, cit, kAm, tAH, viraha, guruRA]
[kaH, cit, kA, AntAH, viraha, guruRA]
[kaH, cit, kAn, tAH, viraha, guruRA]
[kaH, cit, kA, AntA, viraha, guruRA]
[kaH, cit, kA, antAH, viraha, guruRA]
[kaH, cit, kA, antA, A, viraha, guruRA]
[kaH, cit, kA, AntA, A, viraha, guruRA]
[kaH, cit, kA, anta, A, viraha, guruRA]

The expected split [kaH, cit, kAntA, viraha, guruRA] isn't seen. 

The cause is that kAntA isn't in the INRIA db
$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer  kAntA       Input String: kAntA
Input String in SLP1: kAntA
None

**Comment by kmadathil** [comment]
I checked the sanskrit_util branch, which uses a broader set of forms, and we do see the expected split. Time to think of promoting this branch? 

)$ python -m sanskrit_parser.lexical_analyzer.SanskritLexicalAnalyzer --split kaScitkAntAvirahaguruRA --lexical-lookup combined
Input String: kaScitkAntAvirahaguruRA
Input String in SLP1: kaScitkAntAvirahaguruRA
Start Split: 2017-12-22 08:39:41.434973
End DAG generation: 2017-12-22 08:39:42.256790
End pathfinding: 2017-12-22 08:39:42.259057
Splits:
[kas, cit, kAntAs, viraha, guruRA]
[kas, cid, kAntAs, viraha, guruRA]
[kas, cit, kAntA, viraha, guruRA]
[kas, cid, kAntA, viraha, guruRA]
[kas, cit, kAntAs, vi, raha, guruRA]
[kas, cit, kAntAs, viraha, gu, ruRA]
[kas, cid, kAntAs, vi, raha, guruRA]
[kas, cid, kAntAs, viraha, gu, ruRA]
[kas, cit, kAm, tA, viraha, guruRA]
[kas, cit, kAntA, As, viraha, guruRA]

**Comment by avinashvarna** [comment]
I've actually been working on consolidating the forms provided by the sanskrit data library and the inria db and reducing the number of duplicates in the returned results. I can prioritize working on this, since I think it is going to be quite useful and with high benefit. Will work on it this weekend.

**Comment by avinashvarna** [comment]
Just an update on what I've done this weekend:

I spent some time closely following the various sources of data in the sanskrit data project and comparing it with the INRIA db.
1. The verb forms are from the INRIA db with some minor modifications to match them to the MW dictionary dhAtus - This is good, so we don't have to handle verbs separately.
2. ktvA, lyap and tumun forms are from INRIA db as well. So good on that front.
3. Noun forms are predicted based on prAtipadikas from MW dictionary + a table of declension forms for vibhakti, vachana based on anta & linga. These are not from INRIA db, and is consuming most of my time so far.  I've augmented the MW prAtipadikas with prAtipadikas + linga from the INRIA db. Further, I have a script that goes through all ~200K noun forms in INRIA db and checks whether the prAtipadika, linga, vachana, vibhakti in the INRIA db is also predicted by the sanskrit data library. ~20K forms were initially not predicted, because they are special forms, or because the anta+linga combination was not part of the sanskrit data declensions table. I am slowly going through the missing forms and added the appropriate declensions to the table and reduced it to ~13K. I think I will have to either write a script to automate the rest, or as a temporary measure, add the remaining forms as "special" forms to the database, so that they can be correctly looked up/analyzed. The second choice seems reasonable for now. 
Any thoughts?
4. There are a few other forms (samAsapUrvapadas/tasil/kRdantas) in the INRIA db that I have not fully examined yet. Some kRdantas and samAsapUrvapadas are part of the sanskrit data lib as well, so will have to do something similar to the noun forms (i.e. write a script to see if they are already included, and if not, add them).

In the process, I've made some enhancements to reduce duplicate forms. Most of this work is in the Sanskrit data repo itself, which is why I've not pushed any updates to this repo yet.

**Comment by kmadathil** [comment]
3. Let's add "special" forms for now, and keep an open issue to reduce them. 
4. Sounds good.

**Comment by avinashvarna** [comment]
quick update - 
3. Done (added forms from SL_nouns.xml that were not correctly recognized as "special" forms)

All kRdanta forms from SL_parts.xml are now merged in the db as well. There are a few forms that will probably need to be added as special forms.

With all verbs, nouns and kRdantas (participles from parts.xml) included in the db, that should be the bulk of the INRIA data. Will continue to work on checking the other forms, but will also start testing with the updated db to see how it changes the accuracy. Speaking of which, we should probably open an issue to start properly testing the accuracy (using precision/recall, or true/false positive etc.). Our current tests mostly ensure that the library works consistently across py 2.7 and 3.6

**Comment by kmadathil** [comment]
Great.
How do we measure precision/recall for our testsuite? 
Perhaps precision can be defined as the %pass in the UoHD test suite. Perhaps Recall would mean some sort of check if all the reported splits will result in the input sentence after a join?

**Comment by avinashvarna** [comment]
Moved metrics discussion to #84

**Comment by kmadathil** [comment]
How's this going, @avinashvarna 
I've been busy with work, but should be able to get back in a week or two.

**Comment by avinashvarna** [comment]
I have made a reasonable bit of progress in adding forms and metrics, but it's not fully complete. I can push what I've done so far so that others can immediately start using it. 
I've been swamped with work and not been able to spend time on this in the past couple of weeks as well. Hopefully, I can spend some time this weekend to push my progress so far to the repo.

**Comment by avinashvarna** [comment]
I pushed my updates last weekend, but it is causing the tests to fail probably due to longer execution times. I will try to debug the test failures this weekend.

**Comment by kmadathil** [comment]
Let me know how it goes. I've been snowed under with a lot of new stuff and travel in the last two months, and haven't been able to spend any time.

**Comment by codito** [comment]
@avinashvarna @kmadathil I have some time to spare these days (in between projects at work :)). What are our next action items for this branch? Is there anything I can help with?

**Comment by kmadathil** [comment]
@codito - great. I've managed to get swamped by multiple things happening on the personal front. The most glaring need right now is to complete this task - look at the sanskrit_util branch, get everything working on it (may need some test mods) and merge to master.

**Comment by avinashvarna** [comment]
@codito Thanks for volunteering. I've been swamped with things at work, and I have been a bit side-tracked trying to get a seq2seq model working (related to #85 - I have some progress on that front. Now just need to train for a much longer time).

I think this branch should be functional currently - Travis CI tests are [passing](https://travis-ci.org/kmadathil/sanskrit_parser/builds/351622742). As a first step, we can merge with master, and evaluate whether there are a higher number of false negatives in splits. The preliminary results I had showed improved word-level accuracy - https://github.com/kmadathil/sanskrit_parser/tree/sanskrit_util/metrics. I have some scripts to evaluate sentence level accuracy as well, but it takes a long time. @codito Would you be interested in running them?

I was also working on improving the quality of splits by scoring using [sentencepiece](https://github.com/google/sentencepiece), which worked on linux, but I couldn't get it to compile on Windows. If that is something you are interested in, it might be useful as well.

**Comment by codito** [comment]
Thanks for the context. I will start on merging sanskrit_util branch. Re tests, this branch runs a subset of tests compared to master. Is it because of timeouts? Should we get the other tests running before merge?

I'm running the `metrics/word_accuracy_metrics.py` script now. Happy to run the sentence level accuracy scripts too. Please share them.

Sentencepiece looks interesting. @avinashvarna do you have any changes related to scoring with sentencepiece? I will try out windows build.

**Comment by avinashvarna** [comment]
Yes, Since this branch uses stems from the entire Monier-Williams dictionary, it ends up with a lot of candidate splits which increases the running time. I reduced the number of tests in https://github.com/kmadathil/sanskrit_parser/commit/92b17c9762ebddf1c1045a5b0a3ec94dcfd9f661 to prevent the test from timing out on Travis CI.

The sentence level scripts are actually combined with the sentencepiece + word2vec based scoring for now. I created a new scoring branch and pushed my scripts. Let me know if you can run them (Try them on linux first, if you can, since it is quite simple to install sentencepiece there).

**Comment by codito** [comment]
We have a [PR up](https://github.com/kmadathil/sanskrit_parser/pull/90) for merging sanskrit_util to master. Tested the branch with few strings, everything looks good so far. Also added multiprocessing to word accuracy script (completes in ~13mins on 12 core machine). Performance wise combined approach is slower (given the functionality tradeoff, as expected). We can keep performance outside the scope of merging this PR. Thoughts?

Notice a hang with following command at *split* stage, will investigate this further before merge.
```sh
> python -m sanskrit_parser.morphological_analyzer.SanskritMorphologicalAnalyzer "kaScin naro vA nArI vA na aSrImAn na api arUpavAn"
```

Will get to scoring script post merging this.

**Comment by avinashvarna** [comment]
Can we close this, since the PR has been merged?

**Comment by codito** [comment]
We can close this. I don't see a hang in the tokenize by whitespace branch, we are dealing with the issue separately.

**Comment by kmadathil** [comment]
Closing
