### ISSUE TITLE
Online URL

### ISSUE THREAD

**Issue by gasyoun** [kmadathil/sanskrit_parser#99]
At https://github.com/kmadathil/sanskrit_parser can't find a link to see it in action. Is there one?

**Comment by kmadathil** [comment]
https://kmadathil.github.io/sanskrit_parser/ui/index.html (a slightly older version). 
To experience the latest version, please clone the repo, install dependencies and run the following to start a local server: 
```
cd sanskrit_parser/sanskrit_parser/rest_api
python run.py
```
Then access https://kmadathil.github.io/sanskrit_parser/ui/index.html?

**Comment by avinashvarna** [comment]
Should probably add the link in the main README, so that people see it immediately. Also, I've been meaning to setup a cron job on the vedavaapi server to do nightly pulls, so that it is running the latest nightly version. This is a good reminder to do so. I will make the change and update here.

We should add an index.MD in docs/ (Maybe symlink to README?) so that  https://kmadathil.github.io/sanskrit_parser/ does not return 404

**Comment by avinashvarna** [comment]
Adding the index.MD as a symlink doesn't seem to work (at least if the symlink is created on windows). Can track this in a separate issue.

Added link to README, and updated code on REST API server to latest. @gasyoun , please close this issue if satisfied.

**Comment by kmadathil** [comment]
Haven't seen a comment on this - closing for now. @gasyoun  - please reopen if you are not satisfied.
